apiVersion: v1
kind: Service
metadata:
  name: k8s-ai-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: k8s-ai-exporter
spec:
  selector:
    app: k8s-ai-exporter
  ports:
    - name: http
      port: 9100
      targetPort: http

